[tool.semantic_release]
branch = "main"
# version_variable = "your_app/__init__.py:__version__" # Uncomment and modify if you have a __version__ variable
upload_to_pypi = false
upload_to_release = false
