# Generated by Django 5.2.5 on 2025-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
